#!/usr/bin/env python
from wando import ColoredLogsRequestHandler
from os import environ
from sys import argv


if len(argv) == 3 and argv[1] == '--env':
    environ['CONTASDOAPE_ENV'] = argv[2].upper()
else:
    environ['CONTASDOAPE_ENV'] = 'DEVELOPMENT'

from contasdoape.web import app
app.run(request_handler=ColoredLogsRequestHandler)
